name: job_entry
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  firebase_storage: ^12.3.5
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  firebase_database: ^11.0.1
  firebase_app_check: ^0.3.2+5
  firebase_auth: ^5.3.1
  
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  multi_dropdown: ^2.1.4
  printing: ^5.11.0
  path_provider: ^2.0.12
  file_picker: ^8.1.7
  file_saver: ^0.2.14
  permission_handler: ^12.0.1
  csv: ^6.0.0
  pdf: ^3.7.4
  universal_html: ^2.2.4
  list_english_words: 0.2.0
  flutter_colorpicker: ^1.0.3

  css:
    git:
      url: https://github.com/LimbitlessSolutionsInc/css.git
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/test_data.json